### ISSUE TITLE
Upgrading Patchman on Ubuntu 16.04 replaces Apache configuration file

### ISSUE THREAD

**Issue by simonflood** [furlongm/patchman#61]
Upgrading Patchman 1.0.9 to 1.0.12 on Ubuntu Server 16.04 LTS replaced the /etc/apache2/conf-available/patchman.conf thus the "Require ip ..." line I'd added for my installation went AWOL.

Should I be (also) adding that to /etc/patchman/patchman-apache.conf so it gets (re)added when upgrading?

If not, perhaps this file should not be overwritten when upgrading ... ?

Thanks.

**Comment by furlongm** [comment]
This _should_ be fixed in 1.0.16. Please test and let me know how it goes.

**Comment by simonflood** [comment]
Yes 1.0.16 prompted about '/etc/apache2/conf-available/patchman.conf' and '/etc/patchman/local_settings.py'. It also (correctly) didn't overwrite '/etc/patchman/patchman-client.conf '.

What I did notice though is that in 'patchman-apache.conf' (a.k.a 'patchman.conf') ... you 'Define patchman_pythonpath /srv/patchman' which doesn't exist/isn't created on Ubuntu - previously it was using '/usr/lib/python2.7/dist-packages/patchman/'.

Thanks.

**Comment by furlongm** [comment]
`patchman-apache.conf` shouldn't be getting created any more. If it's still there, you can delete it.

That file was meant to be an example file, I've renamed it so that is clearer now.

The files/dir I see getting installed from 1.0.16 are:

```
/etc
/etc/apache2
/etc/apache2/conf-available
/etc/apache2/conf-available/patchman.conf
/etc/patchman
/etc/patchman/local_settings.py
/etc/patchman/apache.conf.example
/etc/cron.daily
/etc/cron.daily/python-patchman
```

and that looks correct to me.

In the postrm on debian, `/srv/patchman` should get replaced by `/usr/lib/python2.7/dist-packages/patchman/'. If you check the final version of the file in `/etc/apache2/conf-available/patchman.conf`m it should have the correct path?

**Comment by furlongm** [comment]
Closing for now. Feel free to reopen if the issue still occurs.
